version: '3.8'

services:
  postgres:
    container_name: barbershop-pg
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: barbershop
      PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK: true
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres